title: Kyle Sang
description: ML & Software Engineer
site_title: '@sang.kyle - Kyle Sang'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Kyle-Sang
email: ksang@terpmail.umd.edu

# absolute or relative
profile_picture: assets/images/pfp.png

# Google Analytics ID
google_analytics: 